name: Noticias Trabalhistas Telegram

on:
  schedule:
    - cron: '0 9 * * *'   # 06:00 BRT
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4 openai

      - name: Rodar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: Salvar histórico
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/enviadas.json
          git commit -m "Atualiza histórico de notícias" || echo "Sem alterações"
          git push
